info:
  medicine:
    cold: drinkwater
    programming: killyourself
server:
  port: 9004
spring:
  data:
    mongodb:
      uri: mongodb://localhost/patients
ccountancy:
  url: http://localhost:9005/patients
